
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no diretório /app do contêiner
      # para que as alterações no código sejam refletidas (hot-reload)
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload